services:
  next:
    image: ghcr.io/alexispe/cesi-cicd/next-image:latest
    ports:
      - "80:3000"

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker/config.json:/config.json
    command: next --interval 30