services:
  next:
    image: ghcr.io/alexispe/cesi-cicd/next-image:latest
    ports:
      - "80:3000"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30 --label-enable